import { z } from "zod";

/**
 * Field types supported by propsto forms.
 * Maps to Prisma FieldType enum.
 */
export const FieldTypeSchema = z.enum([
  "TEXT",
  "TEXTAREA",
  "NUMBER",
  "RATING",
  "SCALE",
  "SELECT",
  "RADIO",
  "CHECKBOX",
  "DATE",
]);

export type FieldType = z.infer<typeof FieldTypeSchema>;

/**
 * A single form field definition.
 * Compatible with TemplateFieldData from @propsto/data.
 */
export const FormFieldSchema = z.object({
  id: z.string().optional(),
  label: z.string(),
  type: FieldTypeSchema,
  required: z.boolean().default(false),
  options: z.array(z.string()).optional(),
  placeholder: z.string().optional(),
  helpText: z.string().optional(),
  order: z.number(),
});

export type FormField = z.infer<typeof FormFieldSchema>;

/**
 * Complete form definition generated by a provider.
 */
export const GeneratedFormSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  fields: z.array(FormFieldSchema),
});

export type GeneratedForm = z.infer<typeof GeneratedFormSchema>;

/**
 * Options for form generation.
 */
export interface GenerateFormOptions {
  /** User's natural language prompt */
  prompt: string;
  /** Optional context about the use case */
  context?: string;
  /** Maximum number of fields to generate */
  maxFields?: number;
}

/**
 * Result from form generation.
 */
export interface GenerateFormResult {
  success: boolean;
  form?: GeneratedForm;
  error?: string;
  /** Raw output from the provider (for debugging) */
  raw?: unknown;
}

/**
 * Partial form for streaming updates.
 * Fields may be incomplete during generation.
 */
export interface PartialGeneratedForm {
  name?: string;
  description?: string;
  fields?: Partial<FormField>[];
}

/**
 * Streaming result callback type.
 */
export type StreamFormCallback = (partial: PartialGeneratedForm) => void;
