/**
 * Server-compatible step completion checks
 * These functions are pure and don't depend on React, so they can be used on both server and client.
 * They're separated from the step component files which have "use client" directives.
 */

import { type User } from "next-auth";

// Organization membership type (matches next-auth User extension)
type OrganizationMembership = {
  organizationId: string;
  organizationSlug: string;
  organizationName: string;
  role: string;
};

// Extended user type with Google Workspace fields
export type WelcomeUser = User & {
  role?: string;
  hostedDomain?: string | null;
  isGoogleWorkspaceAdmin?: boolean;
  pendingLinkToken?: string | null;
  onboardingCompletedAt?: Date | string | null;
  organizations?: OrganizationMembership[];
  personalEmail?: string | null;
  personalEmailVerified?: Date | string | null;
};

// Organization status type
export type OrganizationStatus = "none" | "exists" | "not_exists" | "member";

// Link account status type
export type LinkAccountStatus = "none" | "pending";

/**
 * Check if the link account step is complete
 * This step is only required when there's a pending account link.
 * @param linkStatus - "none" means no pending link (step complete/not needed), "pending" means user must complete linking
 */
export function isLinkAccountStepComplete(
  linkStatus: LinkAccountStatus = "none",
): boolean {
  return linkStatus === "none";
}

/**
 * Check if the personal step data requirements are met
 */
export function isPersonalStepComplete(user: User): boolean {
  return Boolean(
    user.firstName?.trim() && user.lastName?.trim() && user.dateOfBirth,
  );
}

// Check if username is the auto-generated one (user-<uuid> format, 41 chars)
const isAutoGeneratedUsername = (username?: string): boolean => {
  if (!username) return true;
  return username.startsWith("user-") && username.length >= 41;
};

/**
 * Check if the account step data requirements are met
 * User must have a valid username that is not auto-generated
 */
export function isAccountStepComplete(user?: User): boolean {
  if (!user?.username) return false;
  return !isAutoGeneratedUsername(user.username);
}

/**
 * Check if the personal email step is complete
 * This step is only required for Google Workspace users.
 * It's complete when they have a verified personal email linked.
 */
export function isPersonalEmailStepComplete(user?: WelcomeUser): boolean {
  // Non-Google Workspace users skip this step
  if (!user?.hostedDomain) {
    return true;
  }
  // Google Workspace users need a verified personal email
  return Boolean(user.personalEmailVerified);
}

/**
 * Check if the organization step is complete or not required
 * This step is only for Google Workspace admins when no org exists for their domain.
 */
export function isOrganizationStepComplete(
  user?: WelcomeUser,
  orgStatus: OrganizationStatus = "none",
): boolean {
  if (!user?.hostedDomain || orgStatus === "none") {
    return true;
  }
  if (orgStatus === "member") {
    return true;
  }
  if (!user.isGoogleWorkspaceAdmin || orgStatus === "exists") {
    return true;
  }
  return false;
}

/**
 * Check if the organization-join step is complete or not required
 * This step is for users when an organization exists for their domain but they haven't joined yet.
 */
export function isOrganizationJoinStepComplete(
  user?: WelcomeUser,
  orgStatus: OrganizationStatus = "none",
): boolean {
  if (!user?.hostedDomain || orgStatus === "none") {
    return true;
  }
  if (orgStatus === "member") {
    return true;
  }
  if (orgStatus === "not_exists") {
    return true;
  }
  return false;
}

/**
 * Check if the pending-organization step is complete or not required
 * This step is informational only for non-admin users when no org exists for their domain.
 * It's always considered "complete" since user just needs to acknowledge and move on.
 */
export function isPendingOrganizationStepComplete(
  user?: WelcomeUser,
  orgStatus: OrganizationStatus = "none",
): boolean {
  if (!user?.hostedDomain || orgStatus === "none") {
    return true;
  }
  if (orgStatus === "member") {
    return true;
  }
  if (user.isGoogleWorkspaceAdmin || orgStatus === "exists") {
    return true;
  }
  return true;
}

/**
 * Check if the complete step is done
 * This step is complete when the user has finished the onboarding flow
 * (indicated by onboardingCompletedAt being set)
 */
export function isCompleteStepComplete(user?: WelcomeUser): boolean {
  return Boolean(user?.onboardingCompletedAt);
}

/**
 * Map of step names to their completion check functions
 */
export const stepCompletionChecks = {
  "link-account": isLinkAccountStepComplete,
  personal: isPersonalStepComplete,
  account: isAccountStepComplete,
  "personal-email": isPersonalEmailStepComplete,
  organization: isOrganizationStepComplete,
  "organization-join": isOrganizationJoinStepComplete,
  "pending-organization": isPendingOrganizationStepComplete,
  complete: isCompleteStepComplete,
} as const;
