/**
 * Server-compatible step completion checks
 * These functions are pure and don't depend on React, so they can be used on both server and client.
 * They're separated from the step component files which have "use client" directives.
 */

import { type User } from "next-auth";

// Organization membership type (matches next-auth User extension)
type OrganizationMembership = {
  organizationId: string;
  organizationSlug: string;
  organizationName: string;
  role: string;
};

// Extended user type with Google Workspace fields
export type WelcomeUser = User & {
  role?: string;
  hostedDomain?: string | null;
  isGoogleWorkspaceAdmin?: boolean;
  pendingLinkToken?: string | null;
  onboardingCompletedAt?: Date | string | null;
  organizations?: OrganizationMembership[];
  personalEmail?: string | null;
  personalEmailVerified?: Date | string | null;
};

// Organization status type
export type OrganizationStatus = "none" | "exists" | "not_exists" | "member";

// Link account status type
export type LinkAccountStatus = "none" | "pending";

/**
 * Check if the link account step is complete
 * This step is only required when there's a pending account link.
 * @param linkStatus - "none" means no pending link (step complete/not needed), "pending" means user must complete linking
 */
export function isLinkAccountStepComplete(
  linkStatus: LinkAccountStatus = "none",
): boolean {
  return linkStatus === "none";
}

/**
 * Check if the personal step data requirements are met
 */
export function isPersonalStepComplete(user: User): boolean {
  return Boolean(
    user.firstName?.trim() && user.lastName?.trim() && user.dateOfBirth,
  );
}

// Check if username is the auto-generated one (user-<uuid> format, 41 chars)
const isAutoGeneratedUsername = (username?: string): boolean => {
  if (!username) return true;
  return username.startsWith("user-") && username.length >= 41;
};

/**
 * Check if the account step data requirements are met
 * User must have a valid username that is not auto-generated
 */
export function isAccountStepComplete(user?: User): boolean {
  if (!user?.username) return false;
  return !isAutoGeneratedUsername(user.username);
}

/**
 * Check if the personal email step is complete
 * This step is only required for Google Workspace users.
 * It's complete when they have a verified personal email linked.
 */
export function isPersonalEmailStepComplete(user?: WelcomeUser): boolean {
  // Non-Google Workspace users skip this step
  if (!user?.hostedDomain) {
    return true;
  }
  // Google Workspace users need a verified personal email
  return Boolean(user.personalEmailVerified);
}

/**
 * Check if the organization step is complete or not required
 * This step is only for Google Workspace admins when no org exists for their domain.
 */
export function isOrganizationStepComplete(
  user?: WelcomeUser,
  orgStatus: OrganizationStatus = "none",
): boolean {
  if (!user?.hostedDomain || orgStatus === "none") {
    return true;
  }
  if (orgStatus === "member") {
    return true;
  }
  if (!user.isGoogleWorkspaceAdmin || orgStatus === "exists") {
    return true;
  }
  return false;
}

/**
 * Check if the organization-join step is complete or not required
 * This step is for users when an organization exists for their domain but they haven't joined yet.
 */
export function isOrganizationJoinStepComplete(
  user?: WelcomeUser,
  orgStatus: OrganizationStatus = "none",
): boolean {
  if (!user?.hostedDomain || orgStatus === "none") {
    return true;
  }
  if (orgStatus === "member") {
    return true;
  }
  if (orgStatus === "not_exists") {
    return true;
  }
  return false;
}

/**
 * Check if the pending-organization step is complete or not required
 * This step is informational only for non-admin users when no org exists for their domain.
 * It's always considered "complete" since user just needs to acknowledge and move on.
 */
export function isPendingOrganizationStepComplete(
  user?: WelcomeUser,
  orgStatus: OrganizationStatus = "none",
): boolean {
  if (!user?.hostedDomain || orgStatus === "none") {
    return true;
  }
  if (orgStatus === "member") {
    return true;
  }
  if (user.isGoogleWorkspaceAdmin || orgStatus === "exists") {
    return true;
  }
  return true;
}

/**
 * Check if the complete step is done
 * This step is complete when the user has finished the onboarding flow
 * (indicated by onboardingCompletedAt being set)
 */
export function isCompleteStepComplete(user?: WelcomeUser): boolean {
  return Boolean(user?.onboardingCompletedAt);
}

/**
 * Map of step names to their completion check functions
 */
export const stepCompletionChecks = {
  "link-account": isLinkAccountStepComplete,
  personal: isPersonalStepComplete,
  account: isAccountStepComplete,
  "personal-email": isPersonalEmailStepComplete,
  organization: isOrganizationStepComplete,
  "organization-join": isOrganizationJoinStepComplete,
  "pending-organization": isPendingOrganizationStepComplete,
  complete: isCompleteStepComplete,
} as const;

// Step names type for organization steps
export type OrganizationStepName =
  | "organization"
  | "organization-join"
  | "pending-organization";

/**
 * Determine which organization step applies to a user based on their status.
 *
 * Logic:
 * - No hosted domain → null (skip org steps)
 * - Already a member → null (skip org steps)
 * - Admin + org doesn't exist → "organization" (create new org)
 * - Admin + org exists → "organization-join" (join as admin)
 * - Non-admin + org exists → "organization-join" (join as member)
 * - Non-admin + org doesn't exist → "pending-organization" (info only)
 */
export function getOrganizationStep(
  user: WelcomeUser,
  orgStatus: OrganizationStatus,
): OrganizationStepName | null {
  // No Google Workspace domain - skip org steps
  if (!user.hostedDomain || orgStatus === "none") {
    return null;
  }

  // User is already a member of the organization - skip org steps
  if (orgStatus === "member") {
    return null;
  }

  if (user.isGoogleWorkspaceAdmin) {
    // Admin: create org if doesn't exist, join as admin if exists
    return orgStatus === "not_exists" ? "organization" : "organization-join";
  }

  // Non-admin: join if exists, show pending if doesn't exist
  return orgStatus === "exists" ? "organization-join" : "pending-organization";
}

/**
 * Check if all required steps are complete for a user.
 * This is a server-compatible function that can be used in the app package
 * without pulling in React dependencies.
 */
export function areAllStepsComplete(
  user: WelcomeUser,
  orgStatus: OrganizationStatus,
  linkStatus: LinkAccountStatus = "none",
): boolean {
  // Check link-account step
  if (!stepCompletionChecks["link-account"](linkStatus)) {
    return false;
  }

  // Check personal step
  if (!stepCompletionChecks.personal(user as User)) {
    return false;
  }

  // Check account step
  if (!stepCompletionChecks.account(user as User)) {
    return false;
  }

  // Check personal-email step (for Google Workspace users)
  if (!stepCompletionChecks["personal-email"](user)) {
    return false;
  }

  // Check organization-related steps based on what's applicable to this user
  const orgStep = getOrganizationStep(user, orgStatus);
  if (orgStep === "organization") {
    if (!stepCompletionChecks.organization(user, orgStatus)) {
      return false;
    }
  } else if (orgStep === "organization-join") {
    if (!stepCompletionChecks["organization-join"](user, orgStatus)) {
      return false;
    }
  } else if (orgStep === "pending-organization") {
    if (!stepCompletionChecks["pending-organization"](user, orgStatus)) {
      return false;
    }
  }

  // Check complete step (onboarding finished)
  if (!stepCompletionChecks.complete(user)) {
    return false;
  }

  return true;
}
