name: App - Vercel Preview Alias

on: [deployment_status]

concurrency:
  group: deployment-${{ github.event.deployment.id }}-app
  cancel-in-progress: false

jobs:
  new_preview_url:
    runs-on: ubuntu-latest
    if: github.event.deployment.environment == 'Preview – app'
    outputs:
      result: ${{ steps.preview_url.outputs.value }}
      pr_number: ${{steps.get_pr.outputs.pr_number}}
    steps:
      - name: Get Pull Request from Deployment Ref
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEPLOYMENT_SHA="${{ github.event.deployment.sha }}"
          echo "Looking for PR associated with commit $DEPLOYMENT_SHA"

          # Query GitHub API for PR associated with the commit and branch
          PR_DATA=$(gh api repos/${{ github.repository }}/commits/$DEPLOYMENT_SHA/pulls --jq ".[] | .")
          
          # Extract PR number if it exists
          if [ -z "$PR_DATA" ]; then
            echo "No PR associated with commit $DEPLOYMENT_SHA on branch $DEPLOYMENT_REF."
            exit 1
          else
            PR_NUMBER=$(echo "$PR_DATA" | jq '.number')
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi
      - name: Define Preview URL
        id: preview_url
        run: echo "value=app.pr-${{steps.get_pr.outputs.pr_number}}.props.host" >> $GITHUB_OUTPUT
  vercel_alias:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview – app'
    needs: new_preview_url
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Check if cert already exists
        id: check_cert
        run: |
          OUTPUT=$(vercel --scope ${{ vars.VERCEL_TEAM_ID }} certs ls --token ${{ secrets.VERCEL_ACCESS_TOKEN }})
          
          if echo "$OUTPUT" | grep -q "${{needs.new_preview_url.outputs.result}}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Generate Domain Cert in Vercel
        if: steps.check_cert.outputs.exists == 'false'
        run: vercel --scope ${{ vars.VERCEL_TEAM_ID }} cert issue ${{needs.new_preview_url.outputs.result}} --token ${{ secrets.VERCEL_ACCESS_TOKEN }}
      - name: Get Vercel's Alias Preview URL
        id: alias-preview-url
        uses: justincase-jp/vercel-preview-url-alias@0.2.1
        with:
          vercel_access_token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel_team_id: ${{ vars.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ vars.VERCEL_APP_PROJECT_ID }}
          alias_template: ${{needs.new_preview_url.outputs.result}}
      - name: GitHub comment on success
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{needs.new_preview_url.outputs.pr_number}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 App preview deployment successfull at ${{steps.alias-preview-url.outputs.preview_url_alias}}'
            })
  comment_failute:
    if: github.event.deployment_status.state == 'failure'
    needs: new_preview_url
    runs-on: ubuntu-latest
    steps:
      - name: GitHub comment on failute
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{needs.new_preview_url.outputs.pr_number}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🛑 App preview deployment failed'
            })