name: Web - Vercel Preview Alias

permissions:
  pull-requests: write

on: [deployment_status]

concurrency:
  group: deployment-${{ github.event.deployment.id }}-web
  cancel-in-progress: false

jobs:
  set_preview_url:
    name: Set Custom Preview URL
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request from Deployment Ref
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEPLOYMENT_SHA="${{ github.event.deployment.sha }}"
          echo "Looking for PR associated with commit $DEPLOYMENT_SHA"

          # Query GitHub API for PR associated with the commit and branch
          PR_DATA=$(gh api repos/${{ github.repository }}/commits/$DEPLOYMENT_SHA/pulls --jq ".[] | .")
          
          # Extract PR number if it exists
          if [ -z "$PR_DATA" ]; then
            echo "No PR associated with commit $DEPLOYMENT_SHA on branch $DEPLOYMENT_REF."
            exit 1
          else
            PR_NUMBER=$(echo "$PR_DATA" | jq '.number')
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi
      - name: Define Preview URL
        id: preview_url
        if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview - web'
        run: echo "value=web.pr-${{steps.get_pr.outputs.pr_number}}.props.host" >> $GITHUB_OUTPUT
      - name: Install Vercel CLI
        if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview - web'
        run: npm install --global vercel@latest
      - name: Check if cert already exists
        if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview - web'
        id: check_cert
        run: |
          OUTPUT=$(vercel --scope ${{ vars.VERCEL_TEAM_ID }} certs ls --token ${{ secrets.VERCEL_ACCESS_TOKEN }})
          
          if echo "$OUTPUT" | grep -q "${{steps.preview_url.outputs.value}}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Generate Domain Cert in Vercel
        if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview - web' && steps.check_cert.outputs.exists == 'false'
        run: vercel --scope ${{ vars.VERCEL_TEAM_ID }} cert issue ${{steps.preview_url.outputs.value}} --token ${{ secrets.VERCEL_ACCESS_TOKEN }}
      - name: Get Vercel's Alias Preview URL
        id: alias-preview-url
        if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview - web'    
        uses: justincase-jp/vercel-preview-url-alias@0.2.1
        with:
          vercel_access_token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel_team_id: ${{ vars.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ vars.VERCEL_WEB_PROJECT_ID }}
          alias_template: ${{steps.preview_url.outputs.value}}
      - name: GitHub comment on success
        if: steps.alias-preview-url.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{steps.get_pr.outputs.pr_number}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Web preview deployment successfull at ${{steps.alias-preview-url.outputs.preview_url_alias}}'
            })
      - name: GitHub comment on failute
        if: github.event.deployment_status.state == 'failure' && github.event.deployment.environment == 'Preview - web'     
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{steps.get_pr.outputs.pr_number}},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🛑 Web preview deployment failed'
            })